#!/usr/bin/env bash
#u
# Update package list and install nginx
sudo apt-get update
sudo apt-get install -y nginx

# Configure nginx to listen on port 80 and serve the desired content
echo "Holberton School for the win!" | sudo tee /var/www/html/index.html

# Restart nginx using the service command (systemctl is not allowed)
sudo service nginx restart

