#!/usr/bin/env bash
# installs nginx on a remote server and configures it quickly
sudo apt update
sudo apt install nginx -y
sudo touch /var/www/html/index.html
echo "Holberton School" | sudo tee /var/www/html/index.html
sudo service nginx restart
